### PR TITLE
Update community-content.md with TechCrumble Article

### PR DESCRIPTION
**Pull request by arunalakmal**
Update TechCrumble Blog post

### CODE REVIEW

**Comment by andyjeffries** [comment]
Could you possibly change the article to refer to us as "Civo" not "Civo Cloud" (that's not our company name, just our social handle because a lot of networks either wouldn't allow a four letter username, or Civo had already been taken by an individual or a watch manufacturer with the same name). Then I'll merge this in. Thank you.

**Comment by arunalakmal** [comment]
Content has been updated. This should be fine by now, hope you can merge it.

**Comment by arunalakmal** [comment]
Update the article Heading

**Comment by andyjeffries** [comment]
Sorry, I meant the underlying content. It still contains "cluster developed by Civo Cloud". Thanks.

**Comment by arunalakmal** [comment]
should be fine by now. didn't notice that.

**Comment by andyjeffries** [comment]
Thank you, merged :-)

**Pull request merged**
